name: .NET

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      - name: Restore
        run: dotnet restore BcodeSeed.sln
      - name: Build
        run: dotnet build BcodeSeed.sln --no-restore
      - name: Test
        run: dotnet test BcodeSeed.sln --no-build --verbosity normal
